apiVersion: v1
kind: Service
metadata:
  labels:
    app: dhamu-app
  name: dhamu-app-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: dhamu-app
  type: NodePort
