apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dhamu-app
  name: dhamu-app
  namespace: app-testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhamu-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dhamu-app
    spec:
      containers:
      - image: dhamodaranthulasi/argocd:v2
        name: node-app
      imagePullSecrets:
      - name: argocd-integration 
